//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examsys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COURSE()
        {
            this.tbl_RESULT = new HashSet<tbl_RESULT>();
            this.tbl_SEMESTER_DETAILS = new HashSet<tbl_SEMESTER_DETAILS>();
        }
        [Required]
        public string Course_Code { get; set; }
        [Required]
        public string Course_Name { get; set; }
        [Required]
        public string Course_Type { get; set; }

        public Nullable<int> Credit_Hr { get; set; }
        [Required]
        public string Req_Req { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RESULT> tbl_RESULT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SEMESTER_DETAILS> tbl_SEMESTER_DETAILS { get; set; }
    }
}
