//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_STUDENT_AUDIT
    {
        public int Audit_ID { get; set; }
        public Nullable<int> St_ID { get; set; }
        public string ChangeType { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
