//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ExamResults
    {
        public int St_ID { get; set; }
        public string St_Name { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public int Exam_ID { get; set; }
        public string Exam_Type { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> Result_Date { get; set; }
    }
}
