//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examsys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentDetails
    {
        public int St_ID { get; set; }
        public string St_Name { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> Fee_Payment { get; set; }
        public string Department_Name { get; set; }
        public string Course_Name { get; set; }
        public string Course_Type { get; set; }
        public Nullable<int> Credit_Hr { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
